#!/bin/bash

# Git Hook for SwiftLint 

## Run Swiftlint and (auto)fix errors
export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH

SWIFTLINT=$(which swiftlint)

if [[ -e "${SWIFTLINT}" ]]; then
	echo "SwiftLint Start..."
else
	echo "SwiftLint is not present in your environment, download from https://github.com/realm/SwiftLint"
	exit 1
fi

$SWIFTLINT lint --fix