name: Quality of Code

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Generate Quality reports
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.6

      - name: Install Dependencies
        run: |
          brew install lcov

      - name: Build and Run Test
        run: |
          rm -rf .build
          swift package clean
          swift test --enable-code-coverage --build-path $COVERAGE_BUILD_PATH

      - name: Generate LCOV report
        run: |
          ./scripts/gen-lcov-report.sh

      - name: Publish changes in LCOV documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update LCOV report

      - name: Deploy LCOV Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .build/lcov/docs
          allow_empty_commit: true
          destination_dir: ./docs/lcov

      - name: Generate SwiftLint Report
        run: |
          mkdir -p .build/swiftlint
          swiftlint lint --quiet --reporter html > .build/swiftlint/index.html

      - name: Publish changes in SwiftLint documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update SwiftLint report

      - name: Deploy SwiftLint Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .build/swiftlint/
          allow_empty_commit: true
          destination_dir: .build/swiftlint/
